In [1]:
# Include
import matplotlib.pyplot as plt
plt.style.use('classic')
%matplotlib inline
import numpy as np
import pandas as pd
import sklearn as skl
import scipy as sc

In [4]:
# Read in the data
df = pd.read_csv('../Data/OnlineNewsPopularity.csv')
df.head()

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [3]:
# Look at the variables
print(df.info())
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 29 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   parameterWaterBodyCategory                   20000 non-null  object
 1   observedPropertyDeterminandCode              20000 non-null  object
 2   procedureAnalysedFraction                    20000 non-null  object
 3   procedureAnalysedMedia                       20000 non-null  object
 4   resultUom                                    20000 non-null  object
 5   phenomenonTimeReferenceYear                  20000 non-null  int64
 6   parameterSamplingPeriod                      20000 non-null  object
 7   resultMeanValue                              20000 non-null  float64
 8   waterBodyIdentifier                          20000 non-null  object
 9   Country                                      20000 non-null  object
 10  PopulationDensity                            19893 non-null  float64
 11  TerraMarineProtected_2016_2018               19893 non-null  float64
 12  TouristMean_1990_2020                        19893 non-null  float64
 13  VenueCount                                   20000 non-null  float64
 14  netMigration_2011_2018                       19893 non-null  float64
 15  droughts_floods_temperature                  19893 non-null  float64
 16  literacyRate_2010_2018                       19893 non-null  float64
 17  combustibleRenewables_2009_2014              19893 non-null  float64
 18  gdp                                          19893 non-null  float64
 19  composition_food_organic_waste_percent       19893 non-null  float64
 20  composition_glass_percent                    19893 non-null  float64
 21  composition_metal_percent                    19893 non-null  float64
 22  composition_other_percent                    19893 non-null  float64
 23  composition_paper_cardboard_percent          19893 non-null  float64
 24  composition_plastic_percent                  19893 non-null  float64
 25  composition_rubber_leather_percent           19893 non-null  float64
 26  composition_wood_percent                     19893 non-null  float64
 27  composition_yard_garden_green_waste_percent  19893 non-null  float64
 28  waste_treatment_recycling_percent            19893 non-null  float64
dtypes: float64(20), int64(1), object(8)
memory usage: 4.4+ MB
None

,phenomenonTimeReferenceYear,resultMeanValue,PopulationDensity,TerraMarineProtected_2016_2018,TouristMean_1990_2020,VenueCount,netMigration_2011_2018,droughts_floods_temperature,literacyRate_2010_2018,combustibleRenewables_2009_2014,...,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent,waste_treatment_recycling_percent
count,20000.000000,20000.000000,19893.000000,19893.000000,1.989300e+04,20000.000000,19893.000000,19893.000000,19893.000000,19893.000000,...,19893.000000,19893.000000,19893.000000,19893.000000,19893.000000,19893.000000,19893.000000,19893.000000,19893.000000,19893.000000
mean,2008.998700,34.444639,149.895102,26.227472,4.919348e+07,0.141400,114206.842878,0.130027,14.859312,4.652609,...,32.166075,7.663619,3.196126,23.519892,18.903705,11.206789,0.159449,2.073875,1.302482,23.312787
std,1.917859,174.643233,75.994558,6.790095,2.469506e+07,1.922314,144682.517527,0.260679,31.565912,3.444092,...,11.326430,3.279468,1.130070,6.551350,4.252571,4.901386,0.731725,3.013117,3.656386,5.958540
min,1991.000000,0.000015,14.548292,3.875411,5.300380e+05,0.000000,-83749.750000,0.000000,0.000000,1.064468,...,12.780000,2.200000,1.380000,0.000000,5.000000,1.450000,0.000000,0.000000,0.000000,0.760000
25%,2008.000000,0.114100,122.299437,23.733280,2.586796e+07,0.000000,21256.750000,0.005718,0.000000,4.363288,...,30.000000,5.440000,3.000000,17.700000,18.900000,9.000000,0.000000,0.000000,0.000000,22.260000
50%,2009.000000,2.000000,122.299437,30.831906,5.094169e+07,0.000000,75808.375000,0.005718,0.000000,4.457840,...,32.000000,10.000000,3.000000,26.000000,20.000000,9.000000,0.000000,0.000000,0.000000,22.260000
75%,2009.000000,10.975625,137.976566,30.831906,7.117635e+07,0.000000,75808.375000,0.032407,0.000000,4.457840,...,32.000000,10.000000,3.000000,26.000000,20.000000,12.400000,0.000000,2.000000,2.700000,27.250000
max,2017.000000,14108.000000,511.475928,38.767234,7.117635e+07,100.000000,582211.000000,0.729194,87.158924,25.982190,...,62.300000,21.400000,9.200000,44.050000,37.830000,22.900000,6.000000,17.210000,30.460000,47.830000

In [4]:
# Just testing out no impact on clean data
# Frequencies in Actual Order
#dfc1 = df['phenomenonTimeReferenceYear'].value_counts().sort_index()
#print(dfc1)

In [5]:
# This block does not impact the cleaned dataset
# Determine missing Countries
grdbyNC = df.groupby(['observedPropertyDeterminandCode','Country'], dropna=False)

# Calculate frequency and percentage for each group
grdbyNC = grdbyNC.size().reset_index(name='Frequency')

print(grdbyNC)

# Export the DataFrame to a CSV file
#grdbyNC.to_csv('grdbyNC.csv', index=False)

    observedPropertyDeterminandCode  Country  Frequency
0                      CAS_100-41-4    Spain         12
1                      CAS_100-42-5  Ireland          1
2                    CAS_10061-02-6  Ireland          1
3                     CAS_1007-28-9    Spain          1
4                     CAS_1024-57-3    Spain          2
..                              ...      ...        ...
569                   EEA_3164-08-7    Spain        136
570                     EEA_33-06-7    Spain          5
571                     EEA_33-13-6  Germany          1
572                     EEA_33-18-1    Spain          2
573                     EEA_33-64-7    Spain          5

[574 rows x 3 columns]

In [6]:
# Remove all records where Country is missing as multiple varibles per records are missing also
dfClean = df.dropna(subset=['Country'])

# Drop rows where multiple columns are null 
# There are three records, after country is deleted, that have most values null
dfClean = df.dropna(subset=['PopulationDensity', 'TerraMarineProtected_2016_2018', 
                            'TouristMean_1990_2020', 'netMigration_2011_2018', 'droughts_floods_temperature'], how='all')

# Export the DataFrame to a CSV file
#dfClean.to_csv('DropCountry.csv', index=False)

In [7]:
#This block is for determining the uniqueness of the records and identifying duplicates
# This block does not impact the cleaned dataset
# Group data by the five variables
grd_df1 = df.groupby(['Country', 'waterBodyIdentifier','observedPropertyDeterminandCode','phenomenonTimeReferenceYear','resultUom'], dropna=False)

# Calculate frequency for each group
rslt1 = grd_df1.size().reset_index(name='Frequency')

# Sort the result by 'Frequency' in descending order and filter where >1
rslt1 = rslt1.sort_values(by='Frequency', ascending=False)
rslt1 = rslt1[rslt1['Frequency'] > 1]
print(rslt1)

# Export the DataFrame to a CSV file
#rslt1.to_csv('lab1_freq_rslt1.csv', index=False)

       Country waterBodyIdentifier observedPropertyDeterminandCode  \
12149  Romania              ROSO01                  CAS_14798-03-9
12157  Romania              ROSO01                   CAS_7440-47-3
12122  Romania              ROCR01                   EEA_3142-01-6
12118  Romania              ROCR01                  CAS_18785-72-3
12117  Romania              ROCR01                  CAS_16887-00-6
...        ...                 ...                             ...
7256    France           FRGR0143A                  CAS_14797-65-0
8680    France            FRGR0513                  CAS_14265-44-2
3648    France            FRDR2001                   EEA_3164-07-6
13060    Spain    ES030MSPF0318010                   EEA_3161-03-3
6801    France           FRGR0005B                   EEA_3142-01-6

       phenomenonTimeReferenceYear    resultUom  Frequency
12149                         2015    mg{NH4}/L          4
12157                         2015         ug/L          4
12122                         2015        uS/cm          4
12118                         2015         mg/L          4
12117                         2015         mg/L          4
...                            ...          ...        ...
7256                          2009    mg{NO2}/L          2
8680                          2008      mg{P}/L          2
3648                          2008  {massRatio}          2
13060                         2009      mg{N}/L          2
6801                          2009        uS/cm          2

[427 rows x 6 columns]

In [8]:
# Remove duplicate records per the groupby
# Group the filtered DataFrame by 'Country', 'waterBodyIdentifier', 'observedPropertyDeterminandCode', 'phenomenonTimeReferenceYear', 'resultUom'
GrDfClean = dfClean.groupby(['Country', 'waterBodyIdentifier', 'observedPropertyDeterminandCode', 'phenomenonTimeReferenceYear', 'resultUom'])

# Calculate the average of 'resultMeanValue' for each group
averages = GrDfClean['resultMeanValue'].mean().reset_index()

# Merge the calculated averages back into the original DataFrame 'df'
ReducedDF = dfClean.merge(averages, on=['Country', 'waterBodyIdentifier', 'observedPropertyDeterminandCode', 'phenomenonTimeReferenceYear', 'resultUom'], how='left')

# Rename the calculated average of resultMeanValue
if 'resultMeanValue_y' in ReducedDF.columns:
    ReducedDF.rename(columns={'resultMeanValue_y': 'AVGresultMeanValue'}, inplace=True)

# Remove duplicate records based on the specified columns, including 'AVGresultMeanValue'
dfClean = ReducedDF.drop_duplicates(subset=['Country', 'waterBodyIdentifier', 'observedPropertyDeterminandCode', 'phenomenonTimeReferenceYear', 'resultUom', 'AVGresultMeanValue'])

# Reset the index of the DataFrame after removing duplicates
dfClean.reset_index(drop=True, inplace=True)

print(dfClean)

# Export the DataFrame to a CSV file
dfClean.to_csv("../Data/CleanDF.csv")

      parameterWaterBodyCategory observedPropertyDeterminandCode  \
0                             RW                  CAS_14797-65-0
1                             RW                  CAS_14797-65-0
2                             RW                   EEA_3164-07-6
3                             RW                  CAS_14797-55-8
4                             RW                   EEA_3151-01-7
...                          ...                             ...
19422                         RW                  CAS_14797-65-0
19423                         RW                   EEA_3131-01-9
19424                         RW                  CAS_14797-55-8
19425                         RW                   EEA_3164-08-7
19426                         RW                   EEA_3152-01-0

      procedureAnalysedFraction procedureAnalysedMedia    resultUom  \
0                         total                  water    mg{NO2}/L
1                         total                  water    mg{NO2}/L
2                         total                  water  {massRatio}
3                         total                  water    mg{NO3}/L
4                         total                  water       mmol/L
...                         ...                    ...          ...
19422                     total                  water    mg{NO2}/L
19423                     total                  water            %
19424                     total                  water    mg{NO3}/L
19425                     total                  water  {massRatio}
19426                     total                  water         [pH]

       phenomenonTimeReferenceYear parameterSamplingPeriod  resultMeanValue_x  \
0                             2009        2009-01--2009-12           0.063310
1                             2009        2009-01--2009-12           0.046733
2                             2009        2009-01--2009-12         132.859000
3                             2009        2009-01--2009-12          11.578376
4                             2009        2009-01--2009-12           0.206800
...                            ...                     ...                ...
19422                         2009        2009-01--2009-12           0.092466
19423                         2009        2009-01--2009-12          89.908300
19424                         2009        2009-01--2009-12          18.901608
19425                         2009        2009-01--2009-12         307.307000
19426                         2009        2009-01--2009-12           7.954790

                    waterBodyIdentifier Country  ...  \
0                               FRDR609  France  ...
1                               FRFR238  France  ...
2                               FRFR238  France  ...
3                              FRFR327C  France  ...
4      ES014MSPFES-014-NR-038-000-02-02   Spain  ...
...                                 ...     ...  ...
19422                           FRHR239  France  ...
19423                           FRHR239  France  ...
19424                           FRHR241  France  ...
19425                           FRHR241  France  ...
19426                           FRHR241  France  ...

       composition_glass_percent  composition_metal_percent  \
0                           10.0                        3.0
1                           10.0                        3.0
2                           10.0                        3.0
3                           10.0                        3.0
4                            8.0                        3.0
...                          ...                        ...
19422                       10.0                        3.0
19423                       10.0                        3.0
19424                       10.0                        3.0
19425                       10.0                        3.0
19426                       10.0                        3.0

       composition_other_percent  composition_paper_cardboard_percent  \
0                           26.0                                 20.0
1                           26.0                                 20.0
2                           26.0                                 20.0
3                           26.0                                 20.0
4                           14.0                                 15.0
...                          ...                                  ...
19422                       26.0                                 20.0
19423                       26.0                                 20.0
19424                       26.0                                 20.0
19425                       26.0                                 20.0
19426                       26.0                                 20.0

       composition_plastic_percent  composition_rubber_leather_percent  \
0                              9.0                                 0.0
1                              9.0                                 0.0
2                              9.0                                 0.0
3                              9.0                                 0.0
4                              9.0                                 0.0
...                            ...                                 ...
19422                          9.0                                 0.0
19423                          9.0                                 0.0
19424                          9.0                                 0.0
19425                          9.0                                 0.0
19426                          9.0                                 0.0

       composition_wood_percent  composition_yard_garden_green_waste_percent  \
0                           0.0                                          0.0
1                           0.0                                          0.0
2                           0.0                                          0.0
3                           0.0                                          0.0
4                           2.0                                          0.0
...                         ...                                          ...
19422                       0.0                                          0.0
19423                       0.0                                          0.0
19424                       0.0                                          0.0
19425                       0.0                                          0.0
19426                       0.0                                          0.0

       waste_treatment_recycling_percent  AVGresultMeanValue
0                                  22.26            0.063310
1                                  22.26            0.046733
2                                  22.26          132.859000
3                                  22.26           13.358273
4                                  16.84            0.206800
...                                  ...                 ...
19422                              22.26            0.092466
19423                              22.26           89.908300
19424                              22.26           18.901608
19425                              22.26          307.307000
19426                              22.26            7.954790

[19427 rows x 30 columns]

In [9]:
# Look at the cleaned data
print(dfClean.info())
dfClean.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19427 entries, 0 to 19426
Data columns (total 30 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   parameterWaterBodyCategory                   19427 non-null  object
 1   observedPropertyDeterminandCode              19427 non-null  object
 2   procedureAnalysedFraction                    19427 non-null  object
 3   procedureAnalysedMedia                       19427 non-null  object
 4   resultUom                                    19427 non-null  object
 5   phenomenonTimeReferenceYear                  19427 non-null  int64
 6   parameterSamplingPeriod                      19427 non-null  object
 7   resultMeanValue_x                            19427 non-null  float64
 8   waterBodyIdentifier                          19427 non-null  object
 9   Country                                      19427 non-null  object
 10  PopulationDensity                            19427 non-null  float64
 11  TerraMarineProtected_2016_2018               19427 non-null  float64
 12  TouristMean_1990_2020                        19427 non-null  float64
 13  VenueCount                                   19427 non-null  float64
 14  netMigration_2011_2018                       19427 non-null  float64
 15  droughts_floods_temperature                  19427 non-null  float64
 16  literacyRate_2010_2018                       19427 non-null  float64
 17  combustibleRenewables_2009_2014              19427 non-null  float64
 18  gdp                                          19427 non-null  float64
 19  composition_food_organic_waste_percent       19427 non-null  float64
 20  composition_glass_percent                    19427 non-null  float64
 21  composition_metal_percent                    19427 non-null  float64
 22  composition_other_percent                    19427 non-null  float64
 23  composition_paper_cardboard_percent          19427 non-null  float64
 24  composition_plastic_percent                  19427 non-null  float64
 25  composition_rubber_leather_percent           19427 non-null  float64
 26  composition_wood_percent                     19427 non-null  float64
 27  composition_yard_garden_green_waste_percent  19427 non-null  float64
 28  waste_treatment_recycling_percent            19427 non-null  float64
 29  AVGresultMeanValue                           19427 non-null  float64
dtypes: float64(21), int64(1), object(8)
memory usage: 4.4+ MB
None

,phenomenonTimeReferenceYear,resultMeanValue_x,PopulationDensity,TerraMarineProtected_2016_2018,TouristMean_1990_2020,VenueCount,netMigration_2011_2018,droughts_floods_temperature,literacyRate_2010_2018,combustibleRenewables_2009_2014,...,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent,waste_treatment_recycling_percent,AVGresultMeanValue
count,19427.000000,19427.000000,19427.000000,19427.000000,1.942700e+04,19427.000000,19427.000000,19427.000000,19427.000000,19427.000000,...,19427.000000,19427.000000,19427.000000,19427.000000,19427.000000,19427.000000,19427.000000,19427.000000,19427.000000,19427.000000
mean,2008.984712,34.438765,150.899813,26.220845,4.912229e+07,0.138570,116121.244183,0.130505,14.858967,4.609186,...,7.634771,3.204014,23.569207,18.907938,11.256312,0.161015,2.106041,1.318932,23.397886,34.402435
std,1.902932,176.052614,76.385636,6.799202,2.461262e+07,1.840983,145485.174654,0.261142,31.628265,3.401473,...,3.294284,1.138543,6.535184,4.212654,4.936256,0.736417,3.035832,3.663759,5.925362,175.967431
min,1991.000000,0.000015,14.548292,3.875411,5.300380e+05,0.000000,-83749.750000,0.000000,0.000000,1.064468,...,2.200000,1.380000,0.000000,5.000000,1.450000,0.000000,0.000000,0.000000,0.760000,0.000015
25%,2008.000000,0.112859,122.299437,23.733280,2.586796e+07,0.000000,22854.875000,0.005718,0.000000,3.754864,...,5.440000,3.000000,17.700000,18.900000,9.000000,0.000000,0.000000,0.000000,22.260000,0.113062
50%,2009.000000,1.994200,122.299437,30.831906,5.094169e+07,0.000000,75808.375000,0.005718,0.000000,4.457840,...,10.000000,3.000000,26.000000,20.000000,9.000000,0.000000,0.000000,0.000000,22.260000,1.995800
75%,2009.000000,10.884425,205.418372,30.831906,7.117635e+07,0.000000,75808.375000,0.032407,0.000000,4.457840,...,10.000000,3.500000,26.000000,20.000000,12.730000,0.000000,2.370000,2.700000,27.250000,10.888625
max,2017.000000,14108.000000,511.475928,38.767234,7.117635e+07,100.000000,582211.000000,0.729194,87.158924,25.982190,...,21.400000,9.200000,44.050000,37.830000,22.900000,6.000000,17.210000,30.460000,47.830000,14108.000000